### ISSUE TITLE
这是corebook 2021版本的吗？

### ISSUE THREAD

**Issue by zepang** [MaoGT/chuwi_corebook_x14_Hackintosh#1]

**Comment by Lovely-Duck** [comment]
是的

**Comment by zepang** [comment]
oc和支持的版本是啥？我可以用你的吗？

**Comment by Lovely-Duck** [comment]
你可以抄https://github.com/weachy/CoreBookX-14-Hackintosh  作业
但是机型和序列号那里要自己生成一下
https://www.sqlsec.com/2021/08/corebook.html  国光大大的博客也可以看看，我也是跟大佬们抄作业的

**Comment by zepang** [comment]
> 你可以抄https://github.com/weachy/CoreBookX-14-Hackintosh 作业 但是机型和序列号那里要自己生成一下 https://www.sqlsec.com/2021/08/corebook.html 国光大大的博客也可以看看，我也是跟大佬们抄作业的

这两个我都看了，但是王刚大佬这个我尝试了ventura 13.2.1无法正常进入系统，不知道是不是版本问题

**Comment by zepang** [comment]
你目前的oc和系统的版本是多少？

**Comment by Lovely-Duck** [comment]
OC版本现在是0.8.2
系统装的是蒙特雷

**Comment by zepang** [comment]
那跟我目前一样

**Comment by zepang** [comment]
你的电脑也会在开启logo进度条的那个时候有个爆破声音和闪下屏幕吗？

**Comment by Lovely-Duck** [comment]
不会的
